### ISSUE TITLE
Overview general info paragraphs not in rst docs

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-big-data#21]
There is some information here that didn't make it into the rst dev guide: 
http://docs.rackspace.com/cbd/api/v1.0/cbd-devguide-2/content/overview.html

This is a copy and paste of the information if you want to include it anywhere:

Rackspace Cloud Big Data is an on-demand Apache Hadoop service on the Rackspace open cloud. The service supports a RESTful API and alleviates the pain associated with deploying, managing, and scaling Hadoop clusters.

Cloud Big Data is just as flexible and feature-rich as Hadoop. With Cloud Big Data, you benefit from on-demand servers, utility-based pricing, and access to the full set of Hadoop features and APIs. However, you do not have to worry about provisioning, growing, or maintaining your Hadoop infrastructure. The Cloud Big Data service uses an environment that is specifically optimized for Hadoop, which ensures that your jobs run efficiently and reliably. Note that you are still responsible for developing, troubleshooting, and deploying your applications.

The primary use cases for Cloud Big Data are as follows:

    Create on-demand infrastructure for applications in production where physical servers would be too costly and time-consuming to configure and maintain.

    Develop, test, and pilot data analysis applications.

Cloud Big Data provides the following benefits:

    Create or resize Hadoop clusters in minutes and pay only for what you use.

    Access the Hortonworks Data Platform (HDP), an enterprise-ready distribution that is 100 percent Apache open source.

    Provision and manage Hadoop using an easy-to-use Control Panel and a RESTful API.

    Seamlessly access data in Cloud Files containers.

    Gain interoperability with any third party software tool that supports HDP.

    Fanatical Support® on a 24x7x365 basis via chat, phone or ticket.

**Comment by meker12** [comment]
The *About the API* section includes a link to the FAQ, which contains thee same information that was in the Developer Guide. 

I removed the information and replaced it with the link because the information was more generally about the Cloud Big Data service, and not the API.
