### ISSUE TITLE
Create a credential missing some request parm descriptions

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-big-data#23]
There is a second set of request parms for this operation... the example is shown, but not the request parm descriptions for the following:
This list shows the body parameters for the request:

    cloud_files:

        username: Required.

        Cloud Files account user name.
        api_key: Optional.

        API key for the Cloud Files account.

**Comment by meker12** [comment]
Fixed.

**Comment by meker12** [comment]
Fixed.
