### ISSUE TITLE
Stacks description in API Reference part has the Distros description

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-big-data#25]
Stacks has this:

Use the Distros API operations to retrieve the list of supported distributions, their corresponding versions, as well as a list of supported services and components per distribution

Should be something like this:

Stacks are high-level building blocks of software that compose a Big Data architecture. Stacks are comprised of services, which in turn are comprised of components. A stack is specific to a distribution due to the differences in services that are supported across distributions.

**Comment by meker12** [comment]
Fixed.

**Comment by meker12** [comment]
Fixed.
