### ISSUE TITLE
In Create a stack stack.node_groups.components.name parm description appears twice

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-big-data#26]
stack.node_groups.components.name appears twice in the parms list:

stack.node_groups.components.name 	(Required) 	Component name. For example: Namenode
stack.node_groups.count 	(Optional) 	Number of instances of the node group.
stack.node_groups.flavor_id 	(Optional) 	Flavor ID for the node group.
stack.node_groups.components.name 	(Required) 	Component name. For example: Namenode

**Comment by meker12** [comment]
Fixed.
