### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-big-data#36]
The attached Word doc has suggested edits for the release notes. Please let me know if you have any questions. Thanks!
[Cloud Big Data Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-big-data/files/29280/Cloud.Big.Data.Release.Notes_editsKH.docx)

**Comment by meker12** [comment]
Integrated Release Note feedback in PR #37 .
