### ISSUE TITLE
Cloud Big data GS Guide conversion: QE pass: List of issues

### ISSUE THREAD

**Issue by stanzikratel** [rackerlabs/docs-cloud-big-data#39]
The following issues were discovered during the QE pass of the Cloud Big Data GS guide: 

1.	Prerequisites topic: Need to add link for configuring environment variables.
2.	H2 topics need to be changed to gerunds
3.	Delete clusters needs to be changed to Deleting clusters to match other topics
4.	The “Listing clusters” (http://docs.rackspace.com/cbd/api/v1.0/cbd-getting-started-2/content/CDB_listClusters-d1e004.html) topic is missing under “creating and managing Hadoop clusters”

**Comment by meker12** [comment]
Fixed PR #44
