### ISSUE TITLE
Internal doc migration

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-big-data#62]
Determine whether the Cloud Big Data Admin Developer Guide needs to be migrated from docs-internal.rackspace.com website to the new docs-internal landing page.   

http://docs-internal.rackspace.com/cbd/api/v1.0/cbd-mgmt-devguide/content/overview.html

If migration is required, store last PDF in CDN-enabled Cloud Files container and add link to new internal landing page.

**Comment by meker12** [comment]
Sent e-mail to team.

**Comment by meker12** [comment]
Internal dev guide isn't needed anymore.  Attaching the latest PDF so that product team can include it in one wiki. 

[cbd-mgmt-devguide-internal-20150423.pdf](https://github.com/rackerlabs/docs-cloud-big-data/files/161559/cbd-mgmt-devguide-internal-20150423.pdf)

After you've downloaded, please close this issue.  Thanks!

**Comment by rnirmal** [comment]
Thanks @meker12
